name = "ai-calculator"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "frontend"

# Environment variables (development)
[env.development.vars]
BACKEND_URL = "http://localhost:8000"

# Environment variables (production)
# Set in Cloudflare Pages dashboard:
# - BACKEND_URL: Your Railway backend URL (e.g., https://your-app.railway.app)

# Local development
[dev]
port = 8788
local_protocol = "http"
