name = "ai-calculator"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "frontend"

# Environment variables for production
# These should be set in Cloudflare Pages dashboard:
# - BACKEND_URL: Your Railway backend URL (e.g., https://your-app.railway.app)

# Note: For local development, use .dev.vars file instead
# .dev.vars should contain:
# BACKEND_URL=http://localhost:8000
